[build]
builder = "NIXPACKS"
buildCommand = "npx prisma generate && npx tsc -p tsconfig.json"

[deploy]
startCommand = "node dist/src/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
